version: '3'
services:
  eureka-server:
    image: whgao/eureka-server
    ports:
     - "8761:8761"
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        syslog-facility: daemon
        syslog-format: rfc5424
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        
  zuul-server:
    image: whgao/zuul-server
    ports:
     - "9090:9090"
    environment:
      EUREKA_SERVER_HOST: eureka-server
    depends_on:
     - eureka-server
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        syslog-facility: daemon
        syslog-format: rfc5424
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        
  product-service:
    image: whgao/product-service
    environment:
      EUREKA_SERVER_HOST: eureka-server
    depends_on:
     - eureka-server
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        syslog-facility: daemon
        syslog-format: rfc5424
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        
  review-service:
    image: whgao/review-service
    environment:
      EUREKA_SERVER_HOST: eureka-server
    depends_on:
     - eureka-server
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        syslog-facility: daemon
        syslog-format: rfc5424
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

  product-composite-service:
    image: whgao/product-composite-service
    environment:
      EUREKA_SERVER_HOST: eureka-server
    depends_on:
     - eureka-server
     - product-service
     - review-service
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        syslog-facility: daemon
        syslog-format: rfc5424
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
