server:
  port: 9090

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 5  
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/

zuul:
#  prefix: /api
#  Uncomment to disable services automatically registering in Zuul
  ignoredServices: '*'

  routes:
    product:
      path: /product-api/**
      serviceId: product-service
    review:
      path: /review-api/**
      serviceId: review-service
    product-composite:
      path: /composite-api/**
      serviceId: product-composite-service

spring:
  application:
    name: zuul-server

management:
  security:
    enabled: false
