server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

spring:
  application:
    name: product-service

management:
  security:
    enabled: false
    
    

